version: '3.8'

services:
  vllm:
    image: vllm/vllm-openai:latest
    runtime: nvidia
    ipc: host
    ports:
      - "8000:8000"
    environment:
      - HUGGING_FACE_HUB_TOKEN=${HF_TOKEN}
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    command: >
      --model unsloth/Llama-3.2-11B-Vision-Instruct-bnb-4bit
      --dtype half
      --quantization bitsandbytes
      --load_format bitsandbytes
      --max_model_len 13488
      --max_num_seqs 40
      --gpu_memory_utilization 0.99
      --trust-remote-code
      --enforce-eager
      --api-key ${VLLM_API_KEY}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    restart: unless-stopped

  webui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "3000:8080"
    environment:
      - OPENAI_API_KEY=${VLLM_API_KEY}
      - OPENAI_API_BASE_URL=http://vllm:8000/v1
    volumes:
      - open-webui-data:/app/backend/data
    restart: unless-stopped
    depends_on:
      - vllm

volumes:
  open-webui-data:

networks:
  default:
    name: ai-network
    driver: bridge
